services:
  api-equipamentos:
    build: .
    container_name: gestao-ativos-hc
    ports:
      - "8000:8000"
    volumes:
      # Monta o diretório data para persistir o banco de dados
      # Isso garante que os dados persistem mesmo se você desligar o Docker
      - ./data:/app/data
    environment:
      # Variável de ambiente opcional para configurações
      - PYTHONUNBUFFERED=1
    restart: always
